services:

  # App Service
  app:
    build:
      context: .
      dockerfile: .docker/swoole/Dockerfile
    container_name: laravel-octane
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=laravel-mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - OCTANE_SERVER=swoole
    networks:
      - laravel-network
    depends_on:
      - mysql
      - redis

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    networks:
      - laravel-network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Redis Service
  redis:
    image: redis:latest
    container_name: laravel-redis
    ports:
      - "6379:6379"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local